### ISSUE TITLE
Validation error for enzyme information encoded by fragpipe

### ISSUE THREAD

**Issue by levitsky** [bigbio/sdrf-pipelines#176]
I'm trying to validate a file that has `comment[cleavage agent details]` value `NT=Trypsin/P;CS=(?<=[KR])`. This seems fine according to the [spec](https://github.com/bigbio/proteomics-sample-metadata/blob/master/sdrf-proteomics/README.adoc#1032-cleavage-agents) but results in this error:

```python
$ parse_sdrf validate-sdrf --sdrf_file PXD008841.sdrf.tsv 
/home/levitsky/.local/share/pipx/venvs/sdrf-pipelines/lib/python3.11/site-packages/sdrf_pipelines/sdrf/sdrf_schema.py:355: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  validation_results = panda_sdrf.applymap(validate_string)
/home/levitsky/.local/share/pipx/venvs/sdrf-pipelines/lib/python3.11/site-packages/sdrf_pipelines/sdrf/sdrf_schema.py:355: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  validation_results = panda_sdrf.applymap(validate_string)
Traceback (most recent call last):
  File "/home/levitsky/.local/bin/parse_sdrf", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/levitsky/.local/share/pipx/venvs/sdrf-pipelines/lib/python3.11/site-packages/sdrf_pipelines/parse_sdrf.py", line 293, in main
    cli()
  File "/home/levitsky/.local/share/pipx/venvs/sdrf-pipelines/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/levitsky/.local/share/pipx/venvs/sdrf-pipelines/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/levitsky/.local/share/pipx/venvs/sdrf-pipelines/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/levitsky/.local/share/pipx/venvs/sdrf-pipelines/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/levitsky/.local/share/pipx/venvs/sdrf-pipelines/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/levitsky/.local/share/pipx/venvs/sdrf-pipelines/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/levitsky/.local/share/pipx/venvs/sdrf-pipelines/lib/python3.11/site-packages/sdrf_pipelines/parse_sdrf.py", line 187, in validate_sdrf
    errors = errors + df.validate(MASS_SPECTROMETRY, use_ols_cache_only)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/levitsky/.local/share/pipx/venvs/sdrf-pipelines/lib/python3.11/site-packages/sdrf_pipelines/sdrf/sdrf.py", line 92, in validate
    errors = mass_spectrometry_schema.validate(self, use_ols_cache_only=use_ols_cache_only)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/levitsky/.local/share/pipx/venvs/sdrf-pipelines/lib/python3.11/site-packages/sdrf_pipelines/sdrf/sdrf_schema.py", line 218, in validate
    error_ontology_terms = self.validate_columns(panda_sdrf, use_ols_cache_only=use_ols_cache_only)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/levitsky/.local/share/pipx/venvs/sdrf-pipelines/lib/python3.11/site-packages/sdrf_pipelines/sdrf/sdrf_schema.py", line 329, in validate_columns
    errors += column.validate(series)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/levitsky/.local/share/pipx/venvs/sdrf-pipelines/lib/python3.11/site-packages/pandas_schema/column.py", line 27, in validate
    return [error for validation in self.validations for error in validation.get_errors(series, self)]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/levitsky/.local/share/pipx/venvs/sdrf-pipelines/lib/python3.11/site-packages/pandas_schema/column.py", line 27, in <listcomp>
    return [error for validation in self.validations for error in validation.get_errors(series, self)]
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/levitsky/.local/share/pipx/venvs/sdrf-pipelines/lib/python3.11/site-packages/pandas_schema/validation.py", line 85, in get_errors
    simple_validation = ~self.validate(series)
                         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/levitsky/.local/share/pipx/venvs/sdrf-pipelines/lib/python3.11/site-packages/sdrf_pipelines/sdrf/sdrf_schema.py", line 142, in validate
    terms = [ontology_term_parser(x) for x in series.unique()]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/levitsky/.local/share/pipx/venvs/sdrf-pipelines/lib/python3.11/site-packages/sdrf_pipelines/sdrf/sdrf_schema.py", line 142, in <listcomp>
    terms = [ontology_term_parser(x) for x in series.unique()]
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/levitsky/.local/share/pipx/venvs/sdrf-pipelines/lib/python3.11/site-packages/sdrf_pipelines/sdrf/sdrf_schema.py", line 63, in ontology_term_parser
    raise ValueError(
ValueError: Invalid term: cs=(?<=[kr]) after splitting by '=', please check the prefix (e.g. AC, NT, TA..)
```

**Comment by ypriverol** [comment]
Can you take care of this issue @levitsky . I knew the issue but Im now annotating that much the cleavage pattern. I thought at the beginning it was a good idea, but now make the specification verbose and unnecessary. Especially if you consider that 90% of the datasets I have annotated are Trypsin or Trypsin/P. 

BTW, great to have you back in the project.
