### ISSUE TITLE
Add to the Maxquant convert 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/sdrf-pipelines#3]

**Comment by ypriverol** [comment]
@qinchunyuan Thanks fot the first commit. I was testing with the first example and it fails with the following error: 

```
PROCESSING: https://raw.githubusercontent.com/bigbio/proteomics-metadata-standard/master/annotated-projects/PXD000612/sdrf.tsv"
Traceback (most recent call last):
  File "/Users/yperez/local-apps/miniconda3/envs/sdrfcheck/bin/parse_sdrf", line 11, in <module>
    load_entry_point('sdrf-pipelines==0.0.4', 'console_scripts', 'parse_sdrf')()
  File "/Users/yperez/local-apps/miniconda3/envs/sdrfcheck/lib/python3.7/site-packages/sdrf_pipelines-0.0.4-py3.7.egg/sdrf_pipelines/parse_sdrf.py", line 82, in main
  File "/Users/yperez/local-apps/miniconda3/envs/sdrfcheck/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/yperez/local-apps/miniconda3/envs/sdrfcheck/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/yperez/local-apps/miniconda3/envs/sdrfcheck/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/yperez/local-apps/miniconda3/envs/sdrfcheck/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/yperez/local-apps/miniconda3/envs/sdrfcheck/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/yperez/local-apps/miniconda3/envs/sdrfcheck/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/yperez/local-apps/miniconda3/envs/sdrfcheck/lib/python3.7/site-packages/sdrf_pipelines-0.0.4-py3.7.egg/sdrf_pipelines/parse_sdrf.py", line 46, in maxquant_from_sdrf
  File "/Users/yperez/local-apps/miniconda3/envs/sdrfcheck/lib/python3.7/site-packages/sdrf_pipelines-0.0.4-py3.7.egg/sdrf_pipelines/maxquant/maxquant.py", line 1002, in maxquant_convert
IndexError: list index out of range
```

**Comment by ypriverol** [comment]
Add the following parameters to the tool: 

- fastaFilePath: This parameter will enable to inject the protein database into the param.xml `<fastaFilePath></fastaFilePath>`
- matchBetweenRuns: it will allow the user to inject this parameter into maxquant `<matchBetweenRuns>False</matchBetweenRuns>`
- peptideFDR: <peptideFdr>0.01</peptideFdr>
- proteinFDR: <proteinFdr>0.01</proteinFdr>
- tempFolder: <tempFolder></tempFolder>
- numThreads: <numThreads>1</numThreads>

Other small comments: 

All these values should be true: 

```xml
<writeMsScansTable>False</writeMsScansTable>
<writeMsmsScansTable>True</writeMsmsScansTable>
<writePasefMsmsScansTable>True</writePasefMsmsScansTable>
<writeAccumulatedPasefMsmsScansTable>True</writeAccumulatedPasefMsmsScansTable>
<writeMs3ScansTable>True</writeMs3ScansTable>
<writeAllPeptidesTable>True</writeAllPeptidesTable>
<writeMzRangeTable>True</writeMzRangeTable>
<writeMzTab>False</writeMzTab>
```
