### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by enryH** [bigbio/sdrf-pipelines#59]
I tried to run a validation, but got an error on reaching an `ebi.ac.uk` server:

```bash
> parse_sdrf validate-sdrf --sdrf_file .\annotated-projects\PXD011839\sdrf.tsv
Traceback (most recent call last):
  File "c:\users\henry\.conda\envs\metadataproj\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\henry\.conda\envs\metadataproj\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Henry\.conda\envs\metadataproj\Scripts\parse_sdrf.exe\__main__.py", line 7, in <module>
  File "c:\users\henry\.conda\envs\metadataproj\lib\site-packages\sdrf_pipelines\parse_sdrf.py", line 98, in main
    cli()
  File "c:\users\henry\.conda\envs\metadataproj\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\henry\.conda\envs\metadataproj\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\henry\.conda\envs\metadataproj\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\henry\.conda\envs\metadataproj\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\henry\.conda\envs\metadataproj\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\henry\.conda\envs\metadataproj\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\henry\.conda\envs\metadataproj\lib\site-packages\sdrf_pipelines\parse_sdrf.py", line 77, in validate_sdrf
    errors = df.validate(template)
  File "c:\users\henry\.conda\envs\metadataproj\lib\site-packages\sdrf_pipelines\sdrf\sdrf.py", line 52, in validate
    errors = default_schema.validate(self)
  File "c:\users\henry\.conda\envs\metadataproj\lib\site-packages\sdrf_pipelines\sdrf\sdrf_schema.py", line 157, in validate
    error_ontology_terms = self.validate_columns(panda_sdrf)
  File "c:\users\henry\.conda\envs\metadataproj\lib\site-packages\sdrf_pipelines\sdrf\sdrf_schema.py", line 214, in validate_columns
    errors += column.validate(series)
  File "c:\users\henry\.conda\envs\metadataproj\lib\site-packages\pandas_schema\column.py", line 27, in validate
    return [error for validation in self.validations for error in validation.get_errors(series, self)]
  File "c:\users\henry\.conda\envs\metadataproj\lib\site-packages\pandas_schema\column.py", line 27, in <listcomp>
    return [error for validation in self.validations for error in validation.get_errors(series, self)]
  File "c:\users\henry\.conda\envs\metadataproj\lib\site-packages\pandas_schema\validation.py", line 85, in get_errors
    simple_validation = ~self.validate(series)
  File "c:\users\henry\.conda\envs\metadataproj\lib\site-packages\sdrf_pipelines\sdrf\sdrf_schema.py", line 116, in validate
    ontology_terms = client.search(term[TERM_NAME], ontology=self._ontology_name, exact="true")
  File "c:\users\henry\.conda\envs\metadataproj\lib\site-packages\sdrf_pipelines\zooma\ols.py", line 157, in search
    req.raise_for_status()
  File "c:\users\henry\.conda\envs\metadataproj\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://www.ebi.ac.uk/ols/api/search?q=homo+sapiens&exact=on&type=class&ontology=ncbitaxon
```

**Comment by enryH** [comment]
Is python 3.8 strictly required? It solved the problem to go from 3.7 to 3.8.  (Or maybe it did not and the server was just working again)
