### ISSUE TITLE
Error in MaxQuant converter

### ISSUE THREAD

**Issue by foellmelanie** [bigbio/sdrf-pipelines#60]
Hi, 

I tried to run the MaxQuant converter with the sdrf file from here: https://github.com/bigbio/sdrf-pipelines/tree/master/sdrf_pipelines/testdata and a newly downloaded human uniprot fasta file: 

`parse_sdrf convert-maxquant -s sdrf_test.tsv -f /test_uniprot.fasta -m False -pef 0.01 -prf 0.01`

results in: 

`None
PROCESSING: sdrf_test.tsv"
Traceback (most recent call last):
  File "/home/meli/.local/bin/parse_sdrf", line 8, in <module>
    sys.exit(main())
  File "/home/meli/.local/lib/python3.8/site-packages/sdrf_pipelines/parse_sdrf.py", line 98, in main
    cli()
  File "/home/meli/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/meli/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/meli/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/meli/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/meli/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/meli/.local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/meli/.local/lib/python3.8/site-packages/sdrf_pipelines/parse_sdrf.py", line 56, in maxquant_from_sdrf
    Maxquant().maxquant_convert(sdrf, fastafilepath, matchbetweenruns, peptidefdr, proteinfdr,
  File "/home/meli/.local/lib/python3.8/site-packages/sdrf_pipelines/maxquant/maxquant.py", line 690, in maxquant_convert
    tempFolder_node.appendChild(doc.createTextNode(tempFolder))
  File "/usr/lib/python3.8/xml/dom/minidom.py", line 1659, in createTextNode
    raise TypeError("node contents must be a string")
TypeError: node contents must be a string`

Any idea where the error comes from? 

Thanks,
Melanie

**Comment by daichengxin** [comment]
Hi,foellmelanie .Thanks for your testing. This should be the temporary file path is not specified, but I should set a default value, I will fixed these errors. Thanks

**Comment by foellmelanie** [comment]
Hi @daichengxin 

thanks for you feedback. 

Now I set a file path: 

```
parse_sdrf convert-maxquant -s sdrf_test.tsv -f test_uniprot.fasta -m False -pef 0.01 -prf 0.01 -t /tmp
```

and obtain the following error: 

```
None
PROCESSING: sdrf_test.tsv"
Traceback (most recent call last):
  File "/home/meli/.local/bin/parse_sdrf", line 8, in <module>
    sys.exit(main())
  File "/home/meli/.local/lib/python3.8/site-packages/sdrf_pipelines/parse_sdrf.py", line 98, in main
    cli()
  File "/home/meli/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/meli/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/meli/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/meli/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/meli/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/meli/.local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/meli/.local/lib/python3.8/site-packages/sdrf_pipelines/parse_sdrf.py", line 56, in maxquant_from_sdrf
    Maxquant().maxquant_convert(sdrf, fastafilepath, matchbetweenruns, peptidefdr, proteinfdr,
  File "/home/meli/.local/lib/python3.8/site-packages/sdrf_pipelines/maxquant/maxquant.py", line 746, in maxquant_convert
    string.appendChild(doc.createTextNode(raw_Folder + '\\' + key))
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```
Has the code been tested unter Linux? I use Ubuntu 20.04.1 LTS. 

Thanks,
Melanie

**Comment by bgruening** [comment]
I guess this needs to be changes are required=true:

> @click.option('--raw_folder', '-r', help='raw data folder,please use \\')

What does the `\\` mean?

**Comment by daichengxin** [comment]
OK, I only considered running MaxQuant under windows, the mqpar.xml is different between linux and windows.

**Comment by bgruening** [comment]
I assume many Linux users are using the MQ conda package: https://anaconda.org/bioconda/maxquant

**Comment by daichengxin** [comment]
Thanks. I will try to make the mqpar.xml file compatible with both versions @bgruening

**Comment by bgruening** [comment]
Thanks! Please also try to use pathlib wherever possible, then we do not have problems with different path on Unix and Windows.

**Comment by ypriverol** [comment]
@bgruening @foellmelanie we have changed and merge the PR to fix this issue. We are planning to fix another bug related with  OpenMS converter to perform the final release.
